### ISSUE TITLE
support for `WHERE in $1`;

### ISSUE THREAD

**Issue by xoac** [cornucopia-rs/cornucopia#125]
Hi I want to make query that use `WHERE in $1` and obviously `$1` is `&[T]`. Is it possible now?

If yes it would be good to add it as one of examples.

**Comment by xoac** [comment]
O I found it `WHERE sth = ANY($1)` is working. https://github.com/sfackler/rust-postgres/issues/900

So fell free to close this issue or keep to remember about add this as example.

**Comment by LouisGariepy** [comment]
Thanks for reporting!

Interesting! I'll tag this issue for documentation and work on adding it to examples or to the upcoming book.

**Comment by LouisGariepy** [comment]
Looking back at this, it seems to me like this is standard PostgreSQL behavior, and not something that is tied to `rust_postgres` in particular. Since we can't really document every PostgreSQL quirk, I think I'm just going to close this for now.

In the case that I'm wrong and that this is indeed a peculiarity of `rust_postgres`, feel free to tag me, I'll be happy to document it :smile:
