### ISSUE TITLE
error: an inner attribute is not permitted in this context

### ISSUE THREAD

**Issue by ianpurton** [cornucopia-rs/cornucopia#138]
I'm getting the following error from the generated code. If I edit cornucopia.rs directly and make the changes the compiler suggests it works again.

```rust
error: an inner attribute is not permitted in this context
  --> /workspace/target/debug/build/app-62a31f47f074433e/out/cornucopia.rs:5:5
   |
5  |       #![allow(dead_code)]
   |       ^^^^^^^^^^^^^^^^^^^^
6  | /     pub mod types { pub mod public { #[derive( Debug, postgres_types::ToSql, postgres_types::FromSql, Clone, Copy, PartialEq, Eq)]
7  | |                         #[postgres(name = "audit_action")]
8  | |                         pub enum AuditAction { AddMember,DeleteMember,AddSecret,DeleteSecret,AccessSecrets,NewServiceAccount,DeleteServic...
9  | | #[derive( Debug, postgres_types::ToSql, postgres_types::FromSql, Clone, Copy, PartialEq, Eq)]
...  |
16 | |                         #[postgres(name = "permission")]
17 | |                         pub enum Permission { ManageTeam } } }pub mod queries { pub mod audit { use futures::{{StreamExt, TryStreamExt}};...
   | |______________________________________________________________- the inner attribute doesn't annotate this module
   |
   = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files
help: to annotate the module, change the attribute from inner to outer style
   |
5  -     #![allow(dead_code)]
5  +     #[allow(dead_code)]
```

**Comment by LouisGariepy** [comment]
This is a consequence of using the `include!` macro (as I suspect you are doing, please let me know if I'm wrong), and not something specific to Cornucopia. See these issues: https://github.com/rust-lang/rust/issues/66920, https://github.com/rust-lang/rfcs/issues/752.

Until this Rust limitation is solved, one workaround is to use a path annotations instead of `include!`:

```rust
#[path = "path/to/the/generated/cornucopia/module"]
mod cornucopia;
```

Please let me know if this works for you. If not, I have some other ideas up my sleeve, but honestly I'd prefer to keep the attributes as is if possible.

Cheers! Thanks for your interest in Cornucopia.

---

FYI, Changing the attributes from inner (`#![...]`) to outer (`#[...]`) will not work as intended since it will only apply these attributes to the next module. You could manually remove these annotations if you are intent on it (clippy and rustc will produce warnings then, though).

**Comment by ianpurton** [comment]
I think the below doesn't work with `build.rs` as the path changes based on the `OUT_DIR` env var which cargo supplies.

```rust
#[path = "path/to/the/generated/cornucopia/module"]
mod cornucopia;
```

So I wrote some code to do a search and replace on the `#![...]` and now it's working.

**Comment by LouisGariepy** [comment]
@ianpurton I can definitely solve this on our side, so please feel free to reopen this issue at any time if you feel like its troublesome for you. If there's a choice to make between codegen complexity and user experience, I'll always pick user experience! I just wanted to try the `path` method first.

**Comment by jgreenbaum** [comment]
I think it would be great if you could fix this.

**Comment by LouisGariepy** [comment]
I'll fix this as soon as possible :smiley: Should be relatively quick.

**Comment by LouisGariepy** [comment]
I just published a minor release that should fix this issue! Please let me know if there's still something amiss.

Thanks for making Cornucopia better!

**Comment by ianpurton** [comment]
@LouisGariepy Thanks. I've tried it and it works.
