### ISSUE TITLE
Stop formatting generate code

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#92]
Originally, the CLI called `rustfmt` to format the generated code and I proposed an alternative with `prettyplease` which would not use a command and rely on the presence of `rustfmt`. However, as we are not using a token stream, we have to parse the generated code first before formatting it and this has a significant code, about 21% of our test time.

I suggest not formatting the generated code as it is usable without being formatted. For people who need all their code formatted, they should call `rustfmt` themselves (our integration test does this to keep the CI happy).

**Comment by LouisGariepy** [comment]
That is a good point. 21% of runtime is pretty crazy, especially if this includes the db startup/teardown time, migrations etc. In fact its significant enough that I think this should be fixed before 0.8. Good catch.

**Comment by jacobsvante** [comment]
Could `rustfmt` perhaps be introduced as an optional flag? I find standardized formatting on code easier to grasp.

**Comment by LouisGariepy** [comment]
Hi @jacobsvante,

Our conclusion was that users who want consistent formatting already format their code using `cargo fmt`. We didn't see much benefit in making Cornucopia do the formatting separately.

Formatting the generated code directly in Cornucopia has the downsides that you end up duplicating work, since most users will also format project as a whole with `cargo fmt`, and it introduces some failure scenarios because we have to call `rustfmt` using on the `Command` api (`rustfmt` doesn't have a library crate as far as I'm aware).

Please let me know if you have some arguments or use cases to motivate this change! If there is a compelling reason, I'm definitely open to consider adding a flag.

**Comment by jacobsvante** [comment]
Okay, I understand.

The pet peeve I have with this is that the `src/cornucopia.rs` file always shows up as changed in git whenever I regenerate it. Adding 20% extra regeneration time would be a more than a worthy tradeoff for me.

**Comment by LouisGariepy** [comment]
@jacobsvante assuming you have committed a formatted cornucopia file, and then regenerated the file afterwards, the changes go away as soon as you `cargo fmt` again.

If even having the changes temporarily is undesirable, you can always do
```bash
cornucopia ... && cargo fmt
```
which is barely any longer than the hypothetical
```bash
cornucopia --format ...
```

Again, I'm open to adding a format flag, I just want to better understand where you're coming from :smile:

**Comment by jacobsvante** [comment]
True, I think I agree with you 😅

**Comment by LouisGariepy** [comment]
@jacobsvante Alright! I'll keep the issue closed for now then, but don't hesitate if you want us to revisit this issue!
